### ISSUE TITLE
Understanding columnWidth

### ISSUE THREAD

**Issue by brettdewoody** [dowjones/react-cellblock#9]
I'm trying to create a grid with a minimum column width of 40px and gutter width of 20px. To do this I've setup a grid:

```
<Grid columnWidth={40} gutterWidth={20}>
  <Row>
    <Column width="1/10">
      <Avatar text={user.first_name.charAt(0) + user.last_name.charAt(0)} />
    </Column>
    <Column width="9/10">
      <Text bold={true}>{user.first_name} {user.last_name}</Text>
      <Text>{user.email}</Text>
    </Column>
  </Row>
</Grid>
```

When I view the result and collapse the viewport the columns reduce to below 40px in width. According to the docs setting a `columnWidth` should set a min-width for the grid blocks.

Can you help me understand how I can create a Grid containing columns with a min-width of 40px?

**Comment by skiano** [comment]
When you specify "1/10" in your example. It will just divide whatever breakpoint the grid happens to be in into 10 even pieces. So because your grid is falling back to the default breakpoints (4,8,12,16) when the screen is very small, your left column will go down to 4/10 of a grid unit. There is no magic built in that detects when a fraction ends up making a column less than 1 grid unit.

Admittedly, the relationship between fractions and "grid units" can make things confusing. So I made this page to try and help visualize it: https://github.com/dowjones/react-cellblock/blob/master/docs/why-cellblock.md

does that help clarify?

**Comment by brettdewoody** [comment]
Thanks, that's super useful. I'm still seeing some unexpected results however. I'm trying to recreate the [demo page](http://dowjones.github.io/react-cellblock/) but I'm not getting any gutter. Using the code above shouldn't my grid have a gutter width of 20px?

**Comment by skiano** [comment]
You should be yes. When you inspect the elements you should see 10px of padding on the left and right of each column. (a similar method to many other grid systems out there). Are you seeing that?

**Comment by skiano** [comment]
Im going to close this, and we can make a new issue about the outer margin if needed
